language: node_js

node_js:
  - "6"

before_install:
  - npm install
  - npm install -g newman

script:
  - newman run ./job1/First_collection.postman_collection.json
  - newman run ./job1/Second_collection.postman_collection.json
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy-to-gh-pages.sh $TRAVIS_BRANCH
  on:
    all_branches: true